### ISSUE TITLE
Possible bug in bob

### ISSUE THREAD

**Issue by schalkneethling** [mdn/bob#520]
Saw this while working on a different issue in interactive examples. Worth investigating whether this was just a hiccup or a real problem we have just not noticed before 😱 

```bash
MDN-BOB: (mdn-bob.js/@init) Error during build: Error: ENOENT: no such file or directory, open '/Users/schalkneethling/repos/interactive-examples/node_modules/mdn-bob/editor/js/editable-css-bundle.js'
    at Object.openSync (fs.js:465:3)
    at Object.readFileSync (fs.js:368:35)
    at /Users/schalkneethling/repos/interactive-examples/node_modules/mdn-bob/lib/bundler.js:67:31
    at Array.map (<anonymous>)
    at concatSync (/Users/schalkneethling/repos/interactive-examples/node_modules/mdn-bob/lib/bundler.js:67:18)
    at buildBundle (/Users/schalkneethling/repos/interactive-examples/node_modules/mdn-bob/lib/bundler.js:84:18)
    at /Users/schalkneethling/repos/interactive-examples/node_modules/mdn-bob/lib/bundler.js:103:25 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/schalkneethling/repos/interactive-examples/node_modules/mdn-bob/editor/js/editable-css-bundle.js'
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by caugner** [comment]
@schalkneethling Do you remember what command you were running when this issue occurred?

**Comment by schalkneethling** [comment]
Wow, no 😸  I cannot remember. Seeing that this has not come up since I filed it, I reckon closing this is in order.

**Comment by caugner** [comment]
😹
